### ISSUE TITLE
GCode command return nothing

### ISSUE THREAD

**Issue by indexdb** [atanisoft/Esp32FeederController#8]
I try to send Gcode command （ex. M115）from openpnp gcode driver console，got nothing.
Sometimes it returns "ok", most of the time it returns nothing
-----------------------------------------------------------------------
> M115
> M115
> M115
> M115
> M115
> M115
> M612 N1
> M612 N0
> M115
> M115
> M115
> M115
> M115
> M115
> M612 N1
> M612 N1
> M612 N1
> M115
> M115
ok
> M115
> M115
> M115
> M115
> M115
-----------------------------------------------------------------------------
I (27) boot: ESP-IDF v5.0.1-dirty 2nd stage bootloader
I (27) boot: compile time 19:27:32
I (27) boot: chip revision: v1.0
I (30) boot.esp32: SPI Speed      : 40MHz
I (35) boot.esp32: SPI Mode       : DIO
I (39) boot.esp32: SPI Flash Size : 4MB
I (44) boot: Enabling RNG early entropy source...
I (49) boot: Partition Table:
I (53) boot: ## Label            Usage          Type ST Offset   Length
I (60) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (68) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (75) boot:  2 factory          factory app      00 00 00010000 00177000
I (83) boot: End of partition table
I (87) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=4163ch (267836) map
I (192) esp_image: segment 1: paddr=00051664 vaddr=3ffb0000 size=03638h ( 13880) load
I (198) esp_image: segment 2: paddr=00054ca4 vaddr=40080000 size=0b374h ( 45940) load
I (217) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=c4b88h (805768) map
I (508) esp_image: segment 4: paddr=00124bb0 vaddr=4008b374 size=0b50ch ( 46348) load
I (539) boot: Loaded app from partition at offset 0x10000
I (539) boot: Disabling RNG early entropy source...
I (566) main: Esp32FeederController 1 Initializing
I (567) main: Compiled on Mar 31 2023 19:23:37 using IDF v5.0.1-dirty
I (568) main: Running from: factory
I (572) soc_info: Reset reason:power on reset (1), model:ESP32, chip revision:100, number of cores:2, embedded flash:No, embedded PSRAM: No, WiFi:Yes, IEEE 802.15.4:No, BLE:Yes, BT:Yes
I (590) main: Initializing NVS
I (623) wifi_mgr: Setting hostname to "esp32feeder".
I (630) wifi_mgr: Configuring Station (SSID: Wifi-2.4G)
I (630) wifi_mgr: Starting WiFi stack
I (720) wifi_mgr: WiFi station started.
I (1971) wifi_mgr: Connected to SSID: Wifi-2.4G
I (1972) wifi_mgr: [1/36] Waiting for IP address assignment.
I (1996) wifi_mgr: IP address:192.168.1.164
I (1997) wifi_mgr: [2/36] Waiting for IP address assignment.
I (2004) gcode_client_mgr: 0 clients connected
I (2005) gcode_server: Waiting for connections on 192.168.1.164:8989...
I (2013) feeder_mgr: Initializing I2C Bus
W (2015) feeder_mgr: PCA9685(40) was not detected.
W (2019) feeder_mgr: PCA9685(41) was not detected.
W (2025) feeder_mgr: PCA9685(42) was not detected.
I (2032) feeder_mgr: PCA9685(43/0x3ffca198) configured for use.
W (2037) feeder_mgr: PCA9685(44) was not detected.
W (2042) feeder_mgr: PCA9685(45) was not detected.
W (2048) feeder_mgr: PCA9685(46) was not detected.
W (2053) feeder_mgr: PCA9685(47) was not detected.
I (2059) feeder_mgr: Detected PCA9685 devices:1
W (2064) feeder_mgr: MCP23017(20) was not detected!
W (2070) feeder_mgr: MCP23017(21) was not detected!
W (2076) feeder_mgr: MCP23017(22) was not detected!
I (2085) feeder_mgr: MCP23017(23/0x3ffca1d8) configured for use.
W (2088) feeder_mgr: MCP23017(24) was not detected!
W (2093) feeder_mgr: MCP23017(25) was not detected!
W (2099) feeder_mgr: MCP23017(26) was not detected!
W (2104) feeder_mgr: MCP23017(27) was not detected!
I (2109) feeder_mgr: Attempting to create 16 feeders
I (2115) feeder_mgr: Detected 1 PCA9685 and 1 MCP23017
I (2121) feeder_mgr: Creating feeder A593131F (1/0/0/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2131) feeder: [A593131F:1] Initializing using PCA9685 0x3ffca198:0
I (2136) PCA9685: [43:0] Moving to 15 deg
I (2142) feeder_mgr: Enabling feeder A593131F (1)
I (2147) feeder_mgr: Creating feeder 97F4FAD4 (2/0/1/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2156) feeder: [97F4FAD4:2] Initializing using PCA9685 0x3ffca198:1
I (2162) PCA9685: [43:1] Moving to 15 deg
I (2168) feeder_mgr: Enabling feeder 97F4FAD4 (2)
I (2172) feeder_mgr: Creating feeder 0E638528 (3/0/2/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2183) feeder: [0E638528:3] Initializing using PCA9685 0x3ffca198:2
I (2187) PCA9685: [43:2] Moving to 15 deg
I (2193) feeder_mgr: Enabling feeder 0E638528 (3)
I (2198) feeder_mgr: Creating feeder D3C5EB5D (4/0/3/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2207) feeder: [D3C5EB5D:4] Initializing using PCA9685 0x3ffca198:3
I (2213) PCA9685: [43:3] Moving to 15 deg
I (2219) feeder_mgr: Enabling feeder D3C5EB5D (4)
I (2223) feeder_mgr: Creating feeder 775C7838 (5/0/4/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2233) feeder: [775C7838:5] Initializing using PCA9685 0x3ffca198:4
I (2238) PCA9685: [43:4] Moving to 15 deg
I (2244) feeder_mgr: Enabling feeder 775C7838 (5)
I (2249) feeder_mgr: Creating feeder 660C64E1 (6/0/5/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2258) feeder: [660C64E1:6] Initializing using PCA9685 0x3ffca198:5
I (2264) PCA9685: [43:5] Moving to 15 deg
I (2270) feeder_mgr: Enabling feeder 660C64E1 (6)
I (2274) feeder_mgr: Creating feeder 6134C54A (7/0/6/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2284) feeder: [6134C54A:7] Initializing using PCA9685 0x3ffca198:6
I (2290) PCA9685: [43:6] Moving to 15 deg
I (2296) feeder_mgr: Enabling feeder 6134C54A (7)
I (2300) feeder_mgr: Creating feeder D037A224 (8/0/7/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2310) feeder: [D037A224:8] Initializing using PCA9685 0x3ffca198:7
I (2315) PCA9685: [43:7] Moving to 15 deg
I (2321) feeder_mgr: Enabling feeder D037A224 (8)
I (2325) feeder_mgr: Creating feeder E351A565 (9/0/8/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2335) feeder: [E351A565:9] Initializing using PCA9685 0x3ffca198:8
I (2341) PCA9685: [43:8] Moving to 15 deg
I (2346) feeder_mgr: Enabling feeder E351A565 (9)
I (2351) feeder_mgr: Creating feeder AF13AC02 (10/0/9/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2360) feeder: [AF13AC02:10] Initializing using PCA9685 0x3ffca198:9
I (2366) PCA9685: [43:9] Moving to 15 deg
I (2372) feeder_mgr: Enabling feeder AF13AC02 (10)
I (2376) feeder_mgr: Creating feeder C06BE9EC (11/0/10/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2388) feeder: [C06BE9EC:11] Initializing using PCA9685 0x3ffca198:10
I (2392) PCA9685: [43:10] Moving to 15 deg
I (2398) feeder_mgr: Enabling feeder C06BE9EC (11)
I (2402) feeder_mgr: Creating feeder 97FBF52B (12/0/11/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2413) feeder: [97FBF52B:12] Initializing using PCA9685 0x3ffca198:11
I (2418) PCA9685: [43:11] Moving to 15 deg
I (2424) feeder_mgr: Enabling feeder 97FBF52B (12)
I (2428) feeder_mgr: Creating feeder 67703760 (13/0/12/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2438) feeder: [67703760:13] Initializing using PCA9685 0x3ffca198:12
I (2444) PCA9685: [43:12] Moving to 15 deg
I (2450) feeder_mgr: Enabling feeder 67703760 (13)
I (2455) feeder_mgr: Creating feeder E8631392 (14/0/13/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2464) feeder: [E8631392:14] Initializing using PCA9685 0x3ffca198:13
I (2470) PCA9685: [43:13] Moving to 15 deg
I (2476) feeder_mgr: Enabling feeder E8631392 (14)
I (2481) feeder_mgr: Creating feeder E838AF2F (15/0/14/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2491) feeder: [E838AF2F:15] Initializing using PCA9685 0x3ffca198:14
I (2496) PCA9685: [43:14] Moving to 15 deg
I (2502) feeder_mgr: Enabling feeder E838AF2F (15)
I (2507) feeder_mgr: Creating feeder 5CB0F53D (16/0/15/PCA:0x3ffca198/MCP:0x3ffca1d8)
I (2517) feeder: [5CB0F53D:16] Initializing using PCA9685 0x3ffca198:15
I (2522) PCA9685: [43:15] Moving to 15 deg
I (2528) feeder_mgr: Enabling feeder 5CB0F53D (16)
I (2533) feeder_mgr: Configured Feeders:16
I (2538) heap_mon: Heap: 241.09kB / 328.48kB
I (2543) main: Creating 4 worker threads
I (2551) feeder: [A593131F:1] Feeder movement complete, turning off servo
I (2551) feeder: [97F4FAD4:2] Feeder movement complete, turning off servo
I (2551) feeder: [0E638528:3] Feeder movement complete, turning off servo
I (2552) feeder: [D3C5EB5D:4] Feeder movement complete, turning off servo
I (2556) feeder: [775C7838:5] Feeder movement complete, turning off servo
I (2564) feeder: [660C64E1:6] Feeder movement complete, turning off servo
I (2570) feeder: [6134C54A:7] Feeder movement complete, turning off servo
I (2581) feeder: [D037A224:8] Feeder movement complete, turning off servo
I (2588) feeder: [E351A565:9] Feeder movement complete, turning off servo
I (2614) feeder: [AF13AC02:10] Feeder movement complete, turning off servo
I (2552) main: Esp32FeederController Ready!
I (2640) feeder: [C06BE9EC:11] Feeder movement complete, turning off servo
I (2665) feeder: [97FBF52B:12] Feeder movement complete, turning off servo
I (2692) feeder: [67703760:13] Feeder movement complete, turning off servo
I (2718) feeder: [E8631392:14] Feeder movement complete, turning off servo
I (2743) feeder: [E838AF2F:15] Feeder movement complete, turning off servo
I (2769) feeder: [5CB0F53D:16] Feeder movement complete, turning off servo
I (32006) gcode_client_mgr: 0 clients connected
I (32544) heap_mon: Heap: 222.73kB / 328.48kB
I (62009) gcode_client_mgr: 0 clients connected
I (62316) gcode_server: New client:192.168.1.123
I (62549) heap_mon: Heap: 220.05kB / 328.48kB
I (82381) gcode_client: [192.168.1.123] Command:M115
I (86889) gcode_client: [192.168.1.123] Command:M115
I (89963) gcode_client: [192.168.1.123] Command:M115
I (91507) gcode_client: [192.168.1.123] Command:M115
I (92012) gcode_client_mgr: 1 clients connected
I (92318) gcode_client: [192.168.1.123] Command:M115
I (92553) heap_mon: Heap: 219.27kB / 328.48kB
I (94880) gcode_client: [192.168.1.123] Command:M115
I (105227) gcode_client: [192.168.1.123] Command:M612
I (105228) feeder_mgr: feeder status request received
I (122015) gcode_client_mgr: 1 clients connected
I (122557) heap_mon: Heap: 219.40kB / 328.48kB
I (128266) gcode_client: [192.168.1.123] Command:M612
I (128267) feeder_mgr: feeder status request received
I (140553) gcode_client: [192.168.1.123] Command:M115
I (140571) gcode_client: [192.168.1.123] Command:M114
I (152018) gcode_client_mgr: 1 clients connected
I (152562) heap_mon: Heap: 219.04kB / 328.48kB
I (172413) gcode_client: [192.168.1.123] Command:M115
I (174869) gcode_client: [192.168.1.123] Command:M115
I (182021) gcode_client_mgr: 1 clients connected
I (182567) heap_mon: Heap: 219.04kB / 328.48kB
I (212024) gcode_client_mgr: 1 clients connected
I (212570) heap_mon: Heap: 219.13kB / 328.48kB
I (216861) gcode_client: [192.168.1.123] Command:M115
I (242027) gcode_client_mgr: 1 clients connected
I (242573) heap_mon: Heap: 217.38kB / 328.48kB
I (272029) gcode_client_mgr: 1 clients connected
I (272579) heap_mon: Heap: 218.77kB / 328.48kB

**Comment by atanisoft** [comment]
Did you test this from OpenPnP or another client connecting to the endpoint? The M115 command should be returning text, it doesn't print anything on the console when it does though.

**Comment by indexdb** [comment]
yes, I  send gcode from openpnp console and telnet, both of idf.py console and openpnp return nothing.

**Comment by indexdb** [comment]
I checkout the main code, It works. Maybe I use the branch code not main before.
